### ISSUE TITLE
Add animated gif in README ?

### ISSUE THREAD

**Issue by esutton** [novalabio/react-native-maps-super-cluster#1]
Is "clustering" where dense markers spread apart, to allow user to select an individual one?

For example, on Google Earth when trying to select a placemark in a group of densely packed placemarks?

A screenshot or an animated gif would be helpful.

Thank you for sharing your work!

**Comment by 39otrebla** [comment]
The .gif is coming soon. If that won't clarify your doubts, feel free to write us here.

**Comment by 39otrebla** [comment]
FYI, we have a working example as well
https://github.com/novalabio/react-native-maps-super-cluster-example

**Comment by esutton** [comment]
@39otrebla I like your example.  

![simulator screen shot - iphone 6 - 2017-11-15 at 08 54 27](https://user-images.githubusercontent.com/6115047/32842403-9d4bf9b4-c9e2-11e7-900d-3d38eaf7d804.png)


"Clustering" may not be the correct word for what I am seeking.

Use Case:
1) Map is displaying dense overlapping map pin markers.
2) First touch expands markers radially from point of finger touch.
3) Each expanded marker displays a line drawn to original location.  
4) Each expanded marker displays a text keyword to distinguish "Location 101" from "Location 102"
5) Use touches desired marker and callout displays

This sounds challenging.

Thanks again for sharing your work.  Great job!

**Comment by 39otrebla** [comment]
Wrong gif
