### ISSUE TITLE
Cluster callouts

### ISSUE THREAD

**Issue by tonygriv** [novalabio/react-native-maps-super-cluster#10]
I use preserveClusterPressBehavior=false and after onClusterPress would like to show callout above cluster.

But It's seems that task is not trivial with this lib. Any suggestions?

**Comment by 39otrebla** [comment]
Did you try with react-native-maps built-in Callouts?

**Comment by tonygriv** [comment]
I don't completely understand how to use built-in Callouts with these clusters.

**Comment by 39otrebla** [comment]
I apologize, I might have not understood correctly. You are trying to open a callout meant to show the detail of the cluster itself?

**Comment by tonygriv** [comment]
Hmmm... Maybe override renderMarker of ClusteredMapView and that is all

**Comment by 39otrebla** [comment]
Got what you mean. Nope, `renderMarker` wouldn't be enough, but we can try to solve in someway. Our only concern is react-native-maps callaout behavior. Currently is quite buggy (especially on iOS).

Set as enhancement, will work on it in next few days.

**Comment by tonygriv** [comment]
@39otrebla, yes. In callout need to be the slider with the content of the cluster. The content of the cluster can be obtained something like this 

```
const engine = this.mapView.getClusteringEngine()
const children = engine.getChildren(clusterId)
const leaves = engine.getLeaves(clusterId, 'Infinity')
```

And then I need to display it in the cluster callout

**Comment by tonygriv** [comment]
@39otrebla, how are you doing with that? I think, that cluster should be as a common marker with its functionality.

**Comment by 39otrebla** [comment]
We have already found a solution for that and it will be tested right after Christmas.  Releasing and publishing on and npm will most likely happen the 27th or the 28th.

**Comment by 39otrebla** [comment]
See https://github.com/novalabio/react-native-maps-super-cluster/commit/ee4007cc7b4d506fd40ff114bb87684b76870b2a.
