### ISSUE TITLE
Not clustering if markers are on same location

### ISSUE THREAD

**Issue by harishchopra86** [novalabio/react-native-maps-super-cluster#110]
I am using your sdk for clustering markers on maps.
However it is not clustering maps if markers are on same location when multiple markers are on same latitude longitude.

**Comment by thuynt99** [comment]
same issue? have any solution

**Comment by 39otrebla** [comment]
Hi guys. I don't see any solution other than preventing markers to have the exact same coordinates. In one project we did it client-side just by collecting all items with the same coordinates and then slightly modifying them.
