### ISSUE TITLE
Update required to sync up to react life cycle methods update

### ISSUE THREAD

**Issue by amamiri** [novalabio/react-native-maps-super-cluster#112]
This component have to be updated to sync up with react life cycle methods update. See
https://reactjs.org/docs/react-component.html

**Comment by serzh-f** [comment]
Please update the following components: ClusteredMapView

**Comment by deniscreamer** [comment]
@serzh-f 
You can to fork it and fix life cycle methods and update components by himself.
I did it like that.

**Comment by 39otrebla** [comment]
Please see https://github.com/novalabio/react-native-maps-super-cluster/commit/9be68d0f2b3fc1d602ed33efafd42ad6bd934944 .

We've tagged the [v1.7.0-beta-1](https://github.com/novalabio/react-native-maps-super-cluster/tree/v1.7.0-beta-1), is anyone willing to help us test this out? Changes were very deep and we need proper testing before releasing.
