### ISSUE TITLE
[Proposal] Redesign the library as a HoC for MapView

### ISSUE THREAD

**Issue by 39otrebla** [novalabio/react-native-maps-super-cluster#115]
We'll use this issue to collect feedback and track progress down about this redesign.

**Comment by gabimoncha** [comment]
Wouldn't be easier if the library uses supercluster as a hook?

**Comment by 39otrebla** [comment]
@gabrielmoncea please see #126

**Comment by gabimoncha** [comment]
lol. one year later I already forgot why, where and how I was using this library :P
