### ISSUE TITLE
ClusteredMapView crashing in IOS standalone

### ISSUE THREAD

**Issue by jasuno** [novalabio/react-native-maps-super-cluster#121]
I finished my app ready to publish, but when I build the standalone app with expo build:ios the app crashes when it gets to the screen where the map is. I did some tests to make sure that the map was the problem, once I removed the map, the app works as it's supposed to in the standalone version, I also tested by removing all the props of the component but no luck. The component works perfectly in the expo environment, the problem only arises when it comes to the standalone build. Also the map works perfectly fine the android version, both in the expo environment and as the standalone APK ran on a simulator and physical device.

versions  
"react-native-maps-super-cluster": "^1.6.0"
"react-native": "0.62.2"
"react": "16.11.0"
"expo": "^38.0.0"

**Comment by jasuno** [comment]
The problem happened because I was using Google maps on IOS, which requires an API key. instructions are here https://docs.expo.io/versions/latest/sdk/map-view/?redirected

**Comment by Anudnya93** [comment]
In my case location was set to none from simulator -> features -> location -> none, which was causing crash on simulator. I changed it to custom location and given lat and long values
