### ISSUE TITLE
Cannot read property 'longitude' of undefined

### ISSUE THREAD

**Issue by bkniya** [novalabio/react-native-maps-super-cluster#14]
i am installing react-native-maps-super-cluster and put this code in my component
  <ClusteredMapView
                    style={{ flex: 1 }}
                    data={[ {latitude: 41.8962667,longitude: 11.3340056 }]}
                    initialRegion={INIT_REGION}
                    ref={component => { this._map = component; }}
                    renderMarker={this.renderMarker}
                    renderCluster={this.renderCluster} />

but when i run the project i am get this error :
Cannot read property 'longitude' of undefined

how can i fix it ?

**Comment by 39otrebla** [comment]
`data` is supposed to be an array of objects, each of which is supposed to contain a `location` attribute representing a `GeoPoint`. Try replacing your `data` prop with the following:

`data={[ { location: { latitude: 41.8962667,longitude: 11.3340056 } }]}`

Please, see the [props definition](https://github.com/novalabio/react-native-maps-super-cluster#props).

**Comment by bkniya** [comment]
Woww Very fast reply 👍  thank you for reply now it's work and map is showing and markers showing too but clusters not show :| can you help me to fix this problem ? 

![map cluster](https://user-images.githubusercontent.com/6282439/34567066-da6cc038-f171-11e7-9c1a-11bd0f431894.gif)
( hand icons is my markers )

**Comment by PurnimaNaik** [comment]
@39otrebla does it **have** to be "location",  can it be anything else? Say "coordinates"?

**Comment by 39otrebla** [comment]
@PurnimaNaik yes, for now. We have planned to add a prop, something like `locationAccessor: string` which would solve this problem, but it has not been implemented yet. Stay tuned for updates.
