### ISSUE TITLE
undefined is not an object (evaluating 'tree.range')

### ISSUE THREAD

**Issue by GarimaMathur07** [novalabio/react-native-maps-super-cluster#15]
@39otrebla @brunovianarezende @leolusoli   When map scroll is performed then this exception is occurred.

![device-2018-02-09-151254](https://user-images.githubusercontent.com/7220882/36021444-cce17700-0dab-11e8-9e8e-9ae3ac5c5cf5.png)

**Comment by 39otrebla** [comment]
Could you please provide more details on how it happened? By the way, exception is being raised within SuperCluster library, I am not even sure the issue resides on our code base.

**Comment by GarimaMathur07** [comment]
@39otrebla This issue is occurred frequently when we are accessing the map view via scroll or zoom-in & zoom-out. This is a very frequent crash on map and also occurred in showcase application https://github.com/novalabio/react-native-maps-super-cluster-example as well. So, can you please provide the solution of this crash.

**Comment by DanGDroid** [comment]
sorry did not notice but i opened a relevant issue #20

**Comment by 39otrebla** [comment]
We'll look into this asap.

**Comment by 39otrebla** [comment]
Just merged #21, should be fixed. Closing for now.

**Comment by thanh90** [comment]
change the zoom value to integer solved my problem

**Comment by Anudnya93** [comment]
In my case location was set to none from simulator -> features -> location -> none, which was causing crash on simulator. I changed it to custom location and given lat and long values
