### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by GarimaMathur07** [novalabio/react-native-maps-super-cluster#17]
@39otrebla @brunovianarezende @leolusoli This issue is occurred frequently when we are accessing the map view via scroll or zoom-in & zoom-out. This is a very frequent crash on map and also occurred in showcase application https://github.com/novalabio/react-native-maps-super-cluster-example as well. So, can you please provide the solution of this crash.

![device-2018-02-12-113724](https://user-images.githubusercontent.com/7220882/36085425-b1c79e12-0feb-11e8-8eb2-dbb9c5741be1.png)

**Comment by 39otrebla** [comment]
is this still happening?

**Comment by GarimaMathur07** [comment]
@39otrebla yes, require solution for this issue

**Comment by GarimaMathur07** [comment]
@39otrebla Is there any solution for this issue

**Comment by Afsarunnisa** [comment]
Same issue, any solution for that

**Comment by 39otrebla** [comment]
Just merged #21, should be fixed. Closing for now.
