### ISSUE TITLE
Marker image is not updating on android

### ISSUE THREAD

**Issue by vvusts** [novalabio/react-native-maps-super-cluster#18]
I used rn maps in the same way and it works. So I guess that this can be connected with this module (btw thanks for this module :)).
So I want to change marker image when marker is pressed.
And this works on IOS but doesn't work on android.
Implementation is simple on marker press I store it in state and markers are rendered again but should use different image. Problem is that image is not changing on android.
```
renderMarker = (pin) => {
    return (
      <Marker onPress={() => {
        if (this.state.selectedPin && this.state.selectedPin.id == pin.id) {
          this.setState({selectedPin: null});
        } else {
          this.setState({selectedPin: pin});
        }
 
        }} key={pin.id || Math.random()} coordinate={pin.location}>
        {this.selectMarkerImage(pin)}
        
      </Marker> )
    }
```

**Comment by Isko97** [comment]
How did you fix this issue?
