### ISSUE TITLE
custom cluster marker not renders

### ISSUE THREAD

**Issue by DanGDroid** [novalabio/react-native-maps-super-cluster#19]
RN 0.51,
react-native-maps ^0.18.3,
react-native-maps-super-cluster ^1.3.1,

hi,
some time after firs load a custom cluster marker view with an image dose not render , but after changing to next cluster zoom level it renders.

code:
```javascript
  renderCluster = (cluster, onPress) => {
    
        const pointCount = cluster.pointCount,
              coordinate = cluster.coordinate,
              clusterId = cluster.clusterId
    
        const clusterEngine = this.map.getClusteringEngine(),
              clusteredPoints = clusterEngine.getLeaves(clusterId, 100)
              //console.log("FARMERS: "+JSON.stringify(this.getClusterFarmListData(clusteredPoints)))
        let isOpen = this.isStoreOpenInCluster(clusteredPoints)
        let clusterIcon = isOpen ? clusterOpenIcon : clusterCloseIcon
        let clusterTextColor = isOpen ? Colors.booger : Colors.red;
        return (
          <Marker onPress={onPress} coordinate={coordinate} key={cluster.clusterId}>
            <View style={{flex:1}}>
                  <Image source = {clusterIcon}/>
                  <View style={styles.counterTextContainer}>
                    <Text style={[styles.counterText, {color: clusterTextColor}]}>{pointCount}</Text>
                  </View>
            </View>
          </Marker> )
        }
```

![screen shot 2018-02-13 at 10 28 09](https://user-images.githubusercontent.com/10976856/36140073-a2f2e262-10a8-11e8-80a4-760e68381602.png)

**Comment by 39otrebla** [comment]
I do think you should look into [SuperCluster props](https://github.com/novalabio/react-native-maps-super-cluster#props). The problem here might be radius and/or the tile size (extent). Also, have clusters smaller than single markers is anyway not recommended, unless you are able to really fine-tune the radius and extent (for example using ReactNative PixelRatio :) ).
