### ISSUE TITLE
Render Map when API ready

### ISSUE THREAD

**Issue by KapelPTronic** [novalabio/react-native-maps-super-cluster#2]
1.  I want to show a spinner until the data from the api is here, but when i try the code below the pins and the cluster weren't drawn at all. 

```
renderMap() {
    if(this.props.stationsArray.length < 1){
      return(
        <Spinner />
      );
    }

    return (
      <ClusteredMapView
        ref = {(ref)=>this.mapView=ref}
        style={{flex: 1}}
        initialRegion={REGION_HOME}
        data={this.props.stationsArray}
        textStyle={{ color: '#65bc46' }}
        containerStyle={{backgroundColor: 'white', borderColor: '#65bc46'}}
        renderMarker={this.renderPins.bind(this)}
      >
      </ClusteredMapView>
    );
  }
```

2. Is it possible to add an custom pin to the map that is not part of the clusters?

**Comment by 39otrebla** [comment]
1. we'll investigate as soon as possible
2. good catch, we'll add this as soon as possible

Thanks for the feedback!

**Comment by leolusoli** [comment]
Hi @KapelPTronic ,
could you post the code of `this.renderPins` and the structure of the underlying object?

**Comment by KapelPTronic** [comment]
@leolusoli 
```
  renderPins(marker) {
    console.log("renderPins");
    var markerImage = require('../assets/img/marker/marker_77b83a.png');
    return(
      <Marker
        key={marker.uuid}
        coordinate={marker.location}
        image={markerImage}
      >
        <Callout tooltip style={{ flex: 1, position: 'absolute'}} onPress={()=> Actions.detail({marker})}>
          <TouchableOpacity >
            <InfoWindow {...marker} />
          </TouchableOpacity>
        </Callout>
      </Marker>
    );
  }
```

**Comment by 39otrebla** [comment]
Please try first with a standard Marker (and with no custom image) to make sure the issue is actually in this component implementation.

**Comment by KapelPTronic** [comment]
hey, I tried it with the standard Marker but the pins and cluster do not show on the map. the renderPins function don't fire once but only when I show the spinner first. if i comment out the if all works perfectly

by the way thanks for the fast update for the custom marker, works perfectly!!!!

**Comment by 39otrebla** [comment]
@KapelPTronic you are right about first mount after loading spinner, we fixed and releasing soon. Thanks!

**Comment by KapelPTronic** [comment]
@39otrebla nice man, no problem, i have to say thanks 👍

**Comment by KapelPTronic** [comment]
new update works fine!!!

big thanks @39otrebla @leolusoli
