### ISSUE TITLE
How to: group cluster markers

### ISSUE THREAD

**Issue by hanselsen** [novalabio/react-native-maps-super-cluster#24]
For React.js, I use [react-leaflet](https://github.com/PaulLeCam/react-leaflet) and it has a third party lib for creating a `MarkerClusterGroup` called [react-leaflet-markercluster](https://github.com/YUzhva/react-leaflet-markercluster). This enables the map to group different types of markers. Imagine clusters of red and clusters of blue markers.  
Is this possible with this library?

**Comment by 39otrebla** [comment]
I don't think so. In this library markers are clustered together only by geo-coordinates, i.e. no other rationale can be used for clustering.

**Comment by blac3kman** [comment]
@hanselsen Could you provide an example for using 2 supercluster instances?

**Comment by hanselsen** [comment]
Sorry @blac3kman I no longer have access to the code anymore.

**Comment by aravi365** [comment]
@blac3kman  Did you managed to find a solution?
