### ISSUE TITLE
Map not moving on iOS 

### ISSUE THREAD

**Issue by GarimaMathur07** [novalabio/react-native-maps-super-cluster#28]
Using versions:

**"react": "16.0.0-alpha.12",
"react-native": "0.45.1",**

Map not moving on iOS and the map does freeze and stuck. Touch, drag operations are not working on Map. https://github.com/react-community/react-native-maps/issues/1756

**The Error logs are:** 
Could not inset scale from edge 9
Could not inset legal attribution from corner 4

Working on Android is fine.

@39otrebla @DanGDroid Can you please suggest any solution about this issue

**Comment by 39otrebla** [comment]
@GarimaMathur07 latest version of this module depends on react-native-maps@0.20.1. We are using this module with no issues with

- react@16.2.0
- react-native@0.53.3
- react-native-maps@0.20.1

The problem might reside within react-native-maps. Could you please try bump react and react-native dependencies?

**Comment by GarimaMathur07** [comment]
Okay, thanks for the reply. I am closing this issue for now.
