### ISSUE TITLE
Map does not fill screen when changing orientations on device

### ISSUE THREAD

**Issue by Irrelon** [novalabio/react-native-maps-super-cluster#32]
Hey there, I've been trying to solve this one for a couple of days. When using this component and changing from one orientation to the other the map will not fill the screen.

If I switch from this component to the MapView component as a drop-in replacement without changing any other props, the map *does* fill the screen on orientation change.

For some reason it seems that by wrapping the MapView in a ClusteredMapView component, even though in your source you are outputting all the same props with {...this.props} which includes the styling, somehow the underlying MapView doesn't get an update when the orientation changes.

Has anyone else seen this behaviour?

**Comment by marklaatikainen** [comment]
I had same issue and fixed it with event listener, that changes screen width and height to the state and you need to use that state in map.

```
import { Dimensions } from 'react-native';

Dimensions.addEventListener('change', () =>
  this.setState({
    width: Dimensions.get('screen').width,
    height: Dimensions.get('screen').height
  })
);

<ClusteredMapView
width={this.state.width}
height={this.state.height}
 />
```

**Comment by 39otrebla** [comment]
@Irrelon did you give @marklaatikainen 's solution a try?

**Comment by TashaRolland92** [comment]
@39otrebla I did 👋 
Being a complete newb to React Native... it worked first go 💪

**Comment by saransh-malik** [comment]
The above solution didn't work, app crashes when I try adding width and height props to the component.
