### ISSUE TITLE
How to draw route between to points or Adding polyline on the super-cluster?

### ISSUE THREAD

**Issue by luoerming** [novalabio/react-native-maps-super-cluster#35]
Please help me! Thanks you!

# Example
![map](https://user-images.githubusercontent.com/1733426/40097966-abfa7446-590b-11e8-97c6-ba41453442a1.jpg)

**Comment by 39otrebla** [comment]
Inside `<ClusteredMapView />` you can render anything you would render within a normal react-native-maps, so please refer to its official doc for drawing a polyline.
