### ISSUE TITLE
Points at precisely the same location

### ISSUE THREAD

**Issue by edwh** [novalabio/react-native-maps-super-cluster#39]
I've just started to use this library, so apologies if this is a FAQ.

I have a number of data points which are at precisely the same position.  So what happens is that I get a cluster of 4, and I cannot zoom in to separate them out (because even at the maximum zoom level, they're the same location).

Perhaps I should handle this by randomising the location a bit so that the markers aren't in exactly the same position, but is there another way to do this?

**Comment by 39otrebla** [comment]
@edwh unfortunately you already got the point, you should randomise points on your side. Having multiple points on the same coords has nothing to do with clustering and thus there's nothing this library can do for it.

**Comment by edwh** [comment]
Ok, that's fine.  Thanks for your quick reply.

------ Original Message ------

**Comment by 39otrebla** [comment]
Anyway, I will consider adding an API for this specific case. It should have params for tweaking the randomisation though, as different apps may have different needs of randomisation (i.e. distance from the center).

On the meantime, here is a quick help (not tested and written directly to markdown):

```javascript
const RAND_FACTOR = 0.00005 // tweak this

// generate key for lookup map
const getKey = (coords) => `${coords.latitude}:${coords.longitude}`
// randomise, randomisation factor is implicitly contained in max - min
const randomInRange = (min, max) => Math.random() * (max - min) + min

// then create the lookup, something like
let lookupMap = {}
items.forEach((item, index) => {
  const key = getKey(item.coordinates),
            { latitude, longitude } = item.coordinates

  if (lookup.hasOwnProperty(key)) {
    // need randomisation
    items[index].coordinates.latitude = randomInRange(latitude - RAND_FACTOR, latitude + RAND_FACTOR)
    items[index].coordinates.longitude = randomInRange(longitude - RAND_FACTOR, longitude + RAND_FACTOR)
    // remember to add the new (randomised) coords to the lookup
    lookupMap[getKey(items[index].coordinates)] = null
  } else
    lookupMap[key] = null
})
```

Remember to check lat/lng limits if you may have locations near "the end of the world".

**Comment by edwh** [comment]
Thanks.  I think it needs to not be random, otherwise if you rerender 
then markers jump around.  I'll have a play and post back what I end up 
with.

------ Original Message ------

**Comment by edwh** [comment]
Maybe something more like this, which arranges the duplicates round a circle in a deterministic way.  

Probably the performance could be improved.  

```
    arrange(data) {
        const RADIUS = 0.0002

        const getKey = (coords) => `${coords.latitude}:${coords.longitude}`
        const randomInRange = (min, max, seed) => Math.random(seed) * (max - min) + min

        let lookupMap = {}

        // Find out how many points are in the same location.
        data.forEach((item, index) => {
            let key = getKey(item.location);
            if (lookupMap.hasOwnProperty(key)) {
                lookupMap[key]++;
            } else {
                lookupMap[key] = 1;
            }
        });

        // Now put each point which is at the same location around a circle.
        data.forEach((item, index) => {
            let key = getKey(item.location);

            if (lookupMap[key] > 1) {
                let count = 0
                data.forEach((item2, index2) => {
                    let key2 = getKey(item2.location);

                    if (key2 == key) {
                        let angle = count++ / (lookupMap[key] / 2) * Math.PI;
                        let newlat = item2.location.latitude + (RADIUS * Math.cos(angle));
                        let newlng = item2.location.longitude + (RADIUS * Math.sin(angle));
                        data[index2].location.latitude = newlat
                        data[index2].location.longitude = newlng
                    }
                });
            }
        })

        return(data);
    }

```

**Comment by 39otrebla** [comment]
@edwh deterministic calculation is a good point, my example was meant to be used at model level rather than at view level , i.e. either server-side or in your client networking library / API manager. For example when loading paginated results on a map we end up doing `prevData.concat(newData)`, i.e. previous data isn't re-rendered. But of course the deterministic vs random is related to the use case. 

That's by the way one of the reasons why I previously said that different apps may have different needs of randomisation, and that's also why this library may/may not be the best place where to put this feature.

**Comment by otaviogaiao** [comment]
@edwh I'm having this issue. How did you solve it ?

**Comment by edwh** [comment]
@otaviogaiao See the code fragment above.

**Comment by ccoeder** [comment]
Hi @39otrebla , do you have any progress for this?

**Comment by alexsegura** [comment]
There is another possible UI pattern for that which I'm trying to implement. 

1/ Use a `<Callout>` to show details of points at same position
2/ When the `<Callout>` is pressed, use `react-native-modal` (for example) to be able to select one of the items. 

We need to use a modal because you only have one `onPress` handler for the entire `<Callout>` ☹️

The hard part is opening the `<Callout>` only when the cluster is already at max zoom level. 
What do you think?

**Comment by Saad-Bashar** [comment]
any new update on this? having the same effect
