### ISSUE TITLE
There are some props I can not use in react-native-maps-super-cluster 

### ISSUE THREAD

**Issue by DickyKwok** [novalabio/react-native-maps-super-cluster#40]
In MapView, I can use the props as below,
`<MapView
            ref={ref => { this.map = ref; }}
            style={styles.map}
            showsUserLocation = {true}
            followsUserLocation = {false}
            onRegionChangeComplete={this.onRegionChangeComplete}
            // onMapReady={this.onMapReady}
          >`
How can I use these props(showsUserLocation, followsUserLocation, onRegionChangeComplete) in react-native-maps-super-cluster ?

**Comment by grachet** [comment]
if im not wrong, i just add without import or nothing (not my code)

<ClusteredMapView
          showsUserLocation
          userLocationAnnotationTitle='' // to not show the message on click
      
        >

**Comment by leolusoli** [comment]
@DickyKwok The ClusterMap component has all the RN MapView properties. Closing.
