### ISSUE TITLE
fitToCoordinates is not a function

### ISSUE THREAD

**Issue by Josh2941** [novalabio/react-native-maps-super-cluster#42]
I am trying to change the zoom level according to the range of latlngs I have, but when `fitToCoordinates` is called I am getting this error "**fitToCoordinates is not a function**". I tried calling it from `componentDidMount`, `componentDidUpdate` and from `onLayout` callback, but still it throws the same error. When I tried calling it from an async function(this is the place I get the coordinates from an API), it throws the same error as a warning.

**Code:** 
```
fitAllMarkers(coordinatesArray = []) {
    this.map.fitToCoordinates(coordinatesArray, {
      edgePadding: DEFAULT_PADDING,
      animated: true
    });
  }

onLayout() {
    this.fitAllMarkers(this.state.coordinatesArray);
}

render() {
  return <ClusteredMapView
          provider={PROVIDER_GOOGLE}
          minZoomLevel={3}
          data={this.state.data}
          initialRegion={INIT_REGION}
          animateClusters = { true }
          ref={map => { this.map = map; }}
          renderMarker={this.renderMarker}
          renderCluster={this.renderCluster}
          onLayout={() => this.onLayout()}
        />
}
```

**ScreenShot:** 
![screenshot_1531208415](https://user-images.githubusercontent.com/34862136/42496274-1aa3601c-8443-11e8-987e-578de20f372f.png)

**Comment by ccoeder** [comment]
Hello,

I had the same problem. If you look at it, https://github.com/novalabio/react-native-maps-super-cluster/blob/master/ClusteredMapView.js#L56 mapview is shown as a reference.

In this case, such use would be correct.

```
this.map.mapview.fitToCoordinates(coordinatesArray, {
      edgePadding: DEFAULT_PADDING,
      animated: true
    });
```

**Comment by Josh2941** [comment]
@ccoeder, thanks for the reference and suggestion. Works fine :+1:

**Comment by khuznain** [comment]
**step  - 1**
```
constructor(props) {
    super(props);
    this.mapRef = null;
}
```

**step - 2**
```
<ClusteredMapView
          ref={r => {
            this.mapRef = r;
          }}
/>
```

**step - 3** 

 ```
<Marker
      identifier={`pin-${pin.id}`}
      coordinate={pin.location}
      onPress={() => this.mapRef.getMapRef().fitToCoordinates([pin.location], true)}
    />
```

**Comment by taongocson** [comment]
open folder: ~ /node_modules/react-native-maps-super-cluster/ClusteredMapView.js
add lines: 
` onLayout() {
    const listNew = [];
    this.props.data.map((item, index) => {
      listNew.push({
        latitude: item.location.latitude,
        longitude: item.location.longitude,
      });
    });
    this.mapview.fitToCoordinates( listNew, {
      edgePadding: { top: 50, right: 50, bottom: 50, left: 50 },
      animated: true,
    });
  };
`

` <MapView
        {...props}
        style={style}
        ref={this.mapRef}
        onRegionChangeComplete={this.onRegionChangeComplete}
        onLayout={this.onLayout}>
        {`
