### ISSUE TITLE
Clusters are refreshing and forms new clusters on moving map.

### ISSUE THREAD

**Issue by Josh2941** [novalabio/react-native-maps-super-cluster#43]
When the map is moved the clusters are refreshed and forms new clusters. It's not even zoomed-in or zoomed-out. It makes the clusters feel like bug and unstable. It would be better if it is not re-rendered on moving the map.  

**ScreenShot:**

![cluster re-rendered](https://user-images.githubusercontent.com/34862136/42690916-c6031330-86c3-11e8-81f0-1fa9534daa95.gif)

**Comment by leolusoli** [comment]
@Josh2941 Can you share your cluster engine parameters?

**Comment by Josh2941** [comment]
@leolusoli It is the same as provided in the documentation.

```
const pointCount = cluster.pointCount, coordinate = cluster.coordinate, clusterId = cluster.clusterId

    const clusteringEngine = this.map.getClusteringEngine(),
          clusteredPoints = clusteringEngine.getLeaves(clusterId, 100)
```

**Comment by sinodko** [comment]
did you solve your problem? I'm encountering something very similar

**Comment by tomtom94** [comment]
Me I solved this problem like that, and it since works like a charm ;) https://github.com/novalabio/react-native-maps-super-cluster/issues/34#issuecomment-439674456
