### ISSUE TITLE
App Crashes while updating markers with new coordinates when in full zoom level - Android

### ISSUE THREAD

**Issue by Josh2941** [novalabio/react-native-maps-super-cluster#44]
App Crashes while updating markers with new coordinates when in full zoom level. I observed that the crash happens only when a cluster fully is opened and has a more number of coordinates (I had a minimum of > 15) in the same zoomed-in region. 

**This crash occurs only on Android.**

I have provided the error details in the screenshot below. 

**ScreenShot:** 
![Crash cause](https://user-images.githubusercontent.com/34862136/42799507-ba6c062c-89b5-11e8-9116-6ebfd39813ea.png)

**Comment by leolusoli** [comment]
@Josh2941 What does it means "full zoom level"?
The crash happens when you tap the cluster or when you moving the map?
Anyway, i'll make a check asap

**Comment by Josh2941** [comment]
@leolusoli The crash occurs when going through this sequence below. 
1. Tap the cluster so that it zooms to its max zoom level.
2. Update the markers with new coordinates.


I have found a temporary work around to avoid the crash. 
1. Clear out the markers and clusters by assigning it with empty array.
2. If we want to use `fitToCoordinates`, then it should be done now.
3. Then populate the map with new coordinates inside setTimeout().

Example: 
While loading new coordinates:

```
this.setState({ coordinatesArray: [] });
this.map.mapview.fitToCoordinates(coordinatesArray, {
    edgePadding: DEFAULT_PADDING,
    animated: true
});
setTimeout(() => {
    this.setState({ coordinatesArray: newCoordinatesArray });
}, 0);
```

A fix from this package will be more better.

**Comment by mohmdalfaha** [comment]
I am facing a similar issue on Android only, while on iOS it works fine. The issue happens when pressing on a cluster then app crashes immediately. I am not sure the above solution works with my use case. I hope there's a real fix from the authors of this lib.
