### ISSUE TITLE
Delta Value in InitialRegion Ignored on Android

### ISSUE THREAD

**Issue by antpuleo2586** [novalabio/react-native-maps-super-cluster#45]
I'm currently having a problem with the delta value when setting the `inintialRegion`, in that it just seems to ignore it or won't accept the value I give it and instead sets some other value.

Here is my render method code:

```
const INIT_REGION = {
    latitude: 41.8962667,
    longitude: 11.3340056,
    latitudeDelta: 20,
    longitudeDelta: 20,
};

return (<ClusteredMapView
    provider={ MapView.PROVIDER_GOOGLE }
    customMapStyle={ mapStyles }
    initialRegion={ INIT_REGION }
    data={ someData }
    renderMarker={ this.renderMarker }
/>);
```

Actual: 
![screenshot_1534178505](https://user-images.githubusercontent.com/10067589/44045550-bd0afc00-9f20-11e8-82eb-1c175133bb0f.png)

Expected:
![screenshot_1534178726](https://user-images.githubusercontent.com/10067589/44045553-c09c4838-9f20-11e8-9c91-f40741f1fd21.png)

I've tried animating to the region but this only works when I set a timeout of around 500ms, but I don't really want to have to resort to this.

Any ideas?

Using a Pixel 2Xl Emulator on Android Oreo. `v1.4.1` of your package and `v0.21.0` or react native maps.

Thanks and great project!

**Comment by 39otrebla** [comment]
That's wired, we pass that prop as-is via `{...this.props}`, there shouldn't be any difference between our lib and react-native-maps.

**Comment by antpuleo2586** [comment]
This problem seems to have disappeared since making changes regarding when to render in our app i.e. after we know we have attempted to retrieve the user's location, thus setting the `initialRegion` at the right time.

Will close this issue.

Thanks
