### ISSUE TITLE
Setting custom width/height dimensions for a Marker

### ISSUE THREAD

**Issue by JayHuang** [novalabio/react-native-maps-super-cluster#46]
I'm currently having trouble adding some additional space around my cluster markers so I can put the cluster count in the corner.

Setting a negative offset like `top: -10` for my cluster count causes it to get cut off as the Marker itself is not that large. However, setting a larger height for the Marker does not seem to cause any changes in its dimensions.

Perhaps I'm approaching this the wrong way as it seems no one else is having similar issues? Would love some guidance, thanks!

**Comment by 39otrebla** [comment]
Could you please post a code sample? Thanks.

**Comment by JayHuang** [comment]
Yep, no problem. Here's more or less what the code looks like.

```
renderCluster = (cluster, onPress) => {
  const pointCount = cluster.pointCount,
        coordinate = cluster.coordinate,
        clusterId = cluster.clusterId

  const clusteringEngine = this.map.getClusteringEngine(),
        clusteredPoints = clusteringEngine.getLeaves(clusterId, 100)

  return (
    <CustomMarker coordinate={coordinate} onPress={onPress}>
      <View style={styles.clusterCountContainer}>
          <Text style={{color: 'black', fontSize: 9}}>
            {pointCount}
         </Text>
       </View>
    </CustomMarker>
  )
}

const styles = StyleSheet.create({
  clusterCountContainer: {
    position: 'absolute',
    top: 0,
    left: 16,
    width: 20,
    height: 20,
    borderRadius: 20/2,
    borderColor: 'black',
    borderWidth: 1,
    backgroundColor: 'white',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
})



export default class CustomMarker extends Component {
  render() {
    return <Marker {...this.props} image={images.marker} style={{width: 40}}/>
  }
}
```

It renders like this:
![Marker](https://i.imgur.com/fTXVYSP.png)

Adding something like `height: 100` to `Marker` doesn't seem to allow us to achieve the effect intended (having the circle start higher up, about 14px or so above the top of the marker icon.

**Comment by leolusoli** [comment]
@JayHuang Why do you calculate `clusteredPoints` in `renderCluster` method?
