### ISSUE TITLE
Font size for 100+ cluster text

### ISSUE THREAD

**Issue by mgscreativa** [novalabio/react-native-maps-super-cluster#5]
Hi! the font size for the case that the cluster displays 100+ text is too big and overlaps cluster circle. I have reduced it to 18 in ClusterMarker.js and works fine.

**Comment by 39otrebla** [comment]
@mgscreativa thank you for the advice. We are planning to add more granular control on clusters style in the near future (matter of weeks). In particular, we are going to add support for custom scaling of font and cluster size.

Leaving this open until then.
