### ISSUE TITLE
Map become slow when markers are visible

### ISSUE THREAD

**Issue by AlexandreMaistret** [novalabio/react-native-maps-super-cluster#51]
Hello,

I am using this package which I really found really simple ! However, I have noticed performance issues.

Indeed, when I am zooming and dezooming to make appear the clusters or the markers 3 times, the map  starts to be really slow when it shows the markers : when I dezoom, to make appear the clusters, everything goes smooth, but when I zoom again to make appear the markers, the map is again really slow, and each time I do this, it is worse.

At the begining when the map just rendered, everything works fine, it is only when the clusters or the markers have been appeared/disappeared 3 times that the map is getting slow.

I am only rendering 2 markers on the map.

**Comment by leolusoli** [comment]
Hi @AlexandreMaistret, could you make the following tests for me? Repeat the set of the operations checking the CPU usage with a simulator. What platform did you use (iOS/Android/both)?  Are you using custom markers with an `<Image />` inside?

**Comment by AlexandreMaistret** [comment]
Hi @leolusoli 

I am testing on Android, and I have `<Image /> `in my markers. But there is something really strange. Indeed all the markers are `<Image />` and when they are shown, the map is smooth. But  the Clusters are a combinaison of `<View><Text/></View>`, and when there are visible on the map everything is slow.
And what is very strange is if I change the Clusters into `<Image /> `everything is smooth all the time.


Here are the graphs gaved by Android Studio : 

Clusters are `<View><Text/></View>`
![image](https://user-images.githubusercontent.com/14938428/46171919-41d88700-c2a2-11e8-841f-6dfac4b490f9.png)

Clusters are `<Image />`
![image](https://user-images.githubusercontent.com/14938428/46171995-8a904000-c2a2-11e8-8b62-1fd4175fa3e6.png)


Markers code : 

    <View>
        <Marker
          key={this.props.id+ 'marker'}
          coordinate={this.props.coordinate}
          tracksViewChanges={this.props.tracksViewChanges}
          anchor={{ x: 0.5, y: 0.5 }}
          onPress={this.props.onPress}
        >
           <Image
              source={{ uri: this.props.picture_uri }}
              style={styles.PictureStyle}
            />
        </Marker>
        <Circle
          key={this.props.id+ 'circle'}
          radius={this.props.radius}
          center={this.props.coordinate}
          fillColor={this.props.fillColor}
          strokeColor={this.props.strokeColor}
          strokeWidth={3}
        />
    </View>

Clusters code : 

    <Marker
        key={this.props.clusterId}
        coordinate={this.props.coordinate}
        tracksViewChanges={this.props.tracksViewChanges}
        onPress={this.props.onPress}
      >
         <View style={styles.ClusterStyle}>
            <Text style={styles.ClusterTextStyle}>
               {this.props.pointCount}
             </Text>
          </View>
      </Marker>


With Clusters as `<Image />` (Everything is smooth)
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/14938428/46175089-19a15600-c2ab-11e8-96fc-df8c2562b0a3.gif)

With Clusters as `<View><Text/><View/>` (it is slow down when the clusters are visible, but not when the markers are)
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/14938428/46175127-3fc6f600-c2ab-11e8-9a19-872dfdbd8fb5.gif)

**Comment by AlexandreMaistret** [comment]
I have finished to make it work all smooth. I download the latest react-native-maps versions on master.  Now everything works fine !

**Comment by waltershub** [comment]
I'm still having this issue, it works fine on IOS but gets slow on android, it seems that android can't take too many rerenders

**Comment by PurnimaNaik** [comment]
did you figure out a solution @waltershub ? I am facing the same issue. Works great on iOS but terribly slow on android.

**Comment by waltershub** [comment]
@purnkmNaik do not it assume it’s working great on iOS because it’s working smoothly, if you benchmark it in Xcode you’ll see a ton of memory leaks, clustering in react native doesn’t seem to be performant

**Comment by PurnimaNaik** [comment]
Oh 😓

**Comment by EnKrypt** [comment]
This exact issue is still present on Android. Using the latest version of this library did not help.

The map becomes unbearably slow on zooming out, even without custom marker images.

**Comment by fabriziobertoglio1987** [comment]
I am experiencing performances issues when using `react-native-maps-super-cluster` using the latest version of [`react-native-maps v0.24.2`](https://github.com/react-native-community/react-native-maps/tree/v0.24.2). My project is performing very laggy with around 3.000 Markers spread around USA and Asia. The number of markers will increase to 10-30k.

I currently believe the library is not adapt for this, but it did give me the opportunity to learn about [mapbox/supercluster](https://github.com/mapbox/supercluster) and I may try to use that library for some functionality.

I believe some concept on which the library is built are maybe wrong, requiring excessive computing power for resource not even displayed on the map.

The correct logic to build this functionality would be:

1) The user displays the overall map and queries a backend endpoint `/countries` which returns the total number of markers for each country and associated endpoint. 

The response could be
```
[{name: 'Italy', totalMarkers: 1000, endpoint: '/country/1/markers'},{name: 'France',.. }..]
```
The Mobile apps receives the response (**around 20-30 lines of data**) and adds to the map **20-30 markers** with the `total number of spots`.

2) The user clicks on the above country marker for Italy.
- get request to `/country/1/markers` returns the markers for that country
-  `animateCamera` zooms to that specific country

This would improve the performances and it can be further improved to display only the useful markers. 
The [mapbox/supercluster](https://github.com/mapbox/supercluster) library could be used to add some visual effect and aggregate markers to close to each other when the user is fully zoomed in.

A third level for `regions` could be added to `countries` and each request could be limited to 30-40 items.
The performance benefits of caching the total number of items in the backend for regions and countries may be very good.

Hopefully we could discuss about this.

Thanks for the library
