### ISSUE TITLE
No cluster with the specified id

### ISSUE THREAD

**Issue by craigcoles** [novalabio/react-native-maps-super-cluster#52]
### Environment
```
"react": "16.4.1",
"react-native": "0.56.0",
"react-native-maps": "react-community/react-native-maps",
"react-native-maps-super-cluster": "^1.5.0"
```

### Steps to Reproduce
* Using the example provided in the Readme.
* Install the application [either iOS or Android] from fresh.
* Open the application.
* When the clusters are loaded, click on a cluster.

### Expected Behaviour
Upon loading the application and clicking on a cluster, to display the children of the cluster.

### Actual Behaviour
After installing the application from fresh and loading the app, if you click on a cluster its throws the following error:

![](https://user-images.githubusercontent.com/996430/47156747-aace8000-d2df-11e8-864f-0d2f7fed3c9b.png)

![](https://user-images.githubusercontent.com/996430/47159516-f71cbe80-d2e5-11e8-8127-a674b061a1c4.png)

**If you reload the application and try again, no error is encountered and everything works as expected.**

### Notes
* We are using are own `onClusterPress` method to do some do different things depending on the number of children in the cluster: 
```jsx
onClusterPress={this.onClusterPress}
preserveClusterPressBehavior={false}
```

* Inside the `onClusterPress` we are getting the children to see how many there are:
```jsx
onClusterPress = (id: string) => {
    const children = this.map.index
      .getLeaves(id, 100)
      .map(c => c.properties.item);
```

**Comment by ollieh-m** [comment]
The issue seems to be related to having multiple points with exactly the same coordinates. We've explained in this issue on the Supercluster library: https://github.com/mapbox/supercluster/issues/103

But it isn't clear why this error happens on first load of the app, but not if the app is reloaded.

**Comment by craigcoles** [comment]
Turns out, this was down to poor data.

**Comment by bclinkinbeard** [comment]
@craigcoles Can you elaborate? I'm seeing the same behavior with supercluster.

**Comment by craigcoles** [comment]
@bclinkinbeard With the poor data that we had, on first load of the application after install, locations that were `null` were actually being returned as `NaN`. On closing the application and re-opening again, the locations were then being returned as `null` instead.

**Comment by bclinkinbeard** [comment]
@craigcoles Like you were giving supercluster features with `properties.coordinates = [NaN, NaN]`?

**Comment by craigcoles** [comment]
@bclinkinbeard Yeah, I believe that was the issue. For some reason, it was only happening on first load after a fresh install of the application.
