### ISSUE TITLE
GeoJSON feature as item

### ISSUE THREAD

**Issue by danikane** [novalabio/react-native-maps-super-cluster#54]
Hi guys,

In the utils method itemToGeoJSONFeature you perform conversion from lat/lon location to a GeoJSON feature.
https://github.com/novalabio/react-native-maps-super-cluster/blob/master/util.js#L67

What if my item's location property is already a GeoJSON feature?
Currently I have to parse it to conform to this requirement.

I understand it's probably because of the **LatLng** data type for coordinates react-native-maps already uses, but the property's named **coordinate**.

https://github.com/react-community/react-native-maps/blob/master/docs/marker.md#props

**Comment by 39otrebla** [comment]
@danikane thank you for pointing out this. Could you please elaborate more about this statement:

> I understand it's probably because of the LatLng data type for coordinates react-native-maps already uses, but the property's named coordinate.

Thanks.

**Comment by danikane** [comment]
Hi and thanks for the reply.
I mean that the default schema react-native-maps uses for markers for example is a property named **coordinate** of type **LatLng**.

```
type LatLng {
  latitude: Number,
  longitude: Number,
}

```
I meant that current solutions using react-native maps will most probably have to parse their markers geometry in order to switch to the super-cluster.
GeoJSON is a standard and personally I think it's much better to use it (and you do), but there are also people using plain coordinate pairs, objects with lat/lon (lat/lng) etc ... I don't know about the trend. 😄 

I was thinking about a PR with a prop to maybe bypass itemToGeoJSONFeature parser if input feature is indeed a GeoJSON one if my point is relevant. 😃
