### ISSUE TITLE
How can I set width="100%"? style doesn't work.

### ISSUE THREAD

**Issue by gabrielmicko** [novalabio/react-native-maps-super-cluster#57]

**Comment by leolusoli** [comment]
Can you provide the entire affected part of your code?

**Comment by gabrielmicko** [comment]
I would like to have margin or padding from left and right. I can't have it because the map will always be 100% (screen size). So I am not going to see margin from the right.
For example:
```
<View style={{marginLeft: 10, marginRight: 10}}>
    <ClusteredMapView ....>
</View>
```

**Comment by karlis-berzins-accenture** [comment]
I have also noticed that issue.
I have tried even setting fixed width of the map. But it always renders full screen

**Comment by gabrielmicko** [comment]
I have found a not so nice workaround if you are interested I can share it with you. It would be nice if someone could fix it.

**Comment by leolusoli** [comment]
Hi @gabrielmicko @karlis-berzins-accenture .
Sorry for the late reply, i'm fixing right now. The correct behaviour will be available in the next release.

Thank for the tip.
