### ISSUE TITLE
Render Pins on onRegionChangeComplete

### ISSUE THREAD

**Issue by KapelPTronic** [novalabio/react-native-maps-super-cluster#6]
when i only change the region without changeing the zoom level the pins not get rendered correctly.

as example:
i have pins in city 1 and city 2. i start on city 1 with an delta value of 0.25 i see all the pins i need in this area but when i go to the city 2 in another country  there is no pin rendered.

if i zoom in and out the pins get rendered!!

greetings

**Comment by 39otrebla** [comment]
and the underlying dataset is not changing?

**Comment by KapelPTronic** [comment]
nope data is not changing,

i build in an autocomplete input and i use the mapview reference to animate to coordinates
and then there are no pins rendered

**Comment by 39otrebla** [comment]
Thank you for submitting the issue, me and @leolusoli will be looking at it as soon as possible.

**Comment by KapelPTronic** [comment]
thanks @39otrebla i tried to comment out the asking about the zoom level but no changes

**Comment by mgscreativa** [comment]
Great commit I was just about to ask regarding this issue, the clusters indicated the correct amount of markers, but after zoom in some markers were missing! Thanks!

**Comment by KapelPTronic** [comment]
@leolusoli hey, just updated the package over npm but the changes are not included? could that e possible?

**Comment by 39otrebla** [comment]
@KapelPTronic we haven't packed the npm release yet as we'd like to further test the above commit before rolling it out. This should happen tomorrow.

**Comment by 39otrebla** [comment]
@KapelPTronic we've just released v1.1.1 on npm.
