### ISSUE TITLE
Can we access cluster's radius?

### ISSUE THREAD

**Issue by ccoeder** [novalabio/react-native-maps-super-cluster#60]
Hi,

I am trying to add a pagination to my map. When user navigates to map screen I made a api call to just receive markers. And users can get full data when they press to the clusters. 

This is what I want to accomplish. But my problem is, I need to know cluster's location and radius. 

How can I access cluster's radius? I got location, but no other property.

Thank you.

**Comment by 39otrebla** [comment]
@ccoeder you can use `onClusterPress`. It gets passed both `clusterId` (which you can use with SuperCluster instance `getClusteringEngine()`) and `children` of that specific cluster. With `children` data you would have all you need to make other API calls.
