### ISSUE TITLE
ref is not working

### ISSUE THREAD

**Issue by serzh-f** [novalabio/react-native-maps-super-cluster#64]
When I trying set ref to MapView my app crashing. What's happening?

`
<ClusteredMapView ref={(el) => console.log(el)}>
`

But `<View ref={(el) => console.log(el)}>` working. 

    "react-native-maps": "^0.21.0",
    "react-native-maps-super-cluster": "^1.4.1",

**Comment by leolusoli** [comment]
@serzh-f probably, the problem may be that the ref object has fields that are cyclic or, otherwise, unserializable. So `console.log`ing the `ref` may be cause an app crash.

**Comment by serzh-f** [comment]
@leolusoli 

When I trying use this

 `
<ClusteredMapView
...
                    ref={(el) => (this.map = el)}
                >
`
my object this.map is undefined

**Comment by leolusoli** [comment]
@serzh-f where did you test that `this.map` is `undefined`? 
Note, if you console the ref when the component referenced isn't mounted yet, the result is `undefined`.

**Comment by 39otrebla** [comment]
@serzh-f are you still experiencing this?

**Comment by RNTop** [comment]
I've faced the same issue

**Comment by Changeun-Noah-Song** [comment]
@LeeHyangTom you can access the original MapView which is included in ClusteredMapView by `mapview` variable. I assigned ClusteredMapView as map `<ClusteredMapView ref={map => { this.map = map }} />` and then accessed the mapview like this `this.map.mapview`.

if you can see ClusteredMapView.js, you would know how it assigned `<MapView />` to access

this is from 
```
  mapRef(ref) {
    this.mapview = ref
  }

  getMapRef() {
    return this.mapview
  }
```

**Comment by spyshower** [comment]
Any news on this?

**Comment by kimkong88** [comment]
I am experiencing this too
`                    ref={(ref) => (this.mapView = ref)}
                    onMapReady={() => console.log(this.mapView)}`
mapView is undefined

edit: 

ref={(ref) => console.log(ref)} also undefined

edit: 

tried with mapRef, no longer undefined.

**Comment by armandojacobus** [comment]
> this.map.mapview

Tnx !

Just replace this.map with this.map.mapview (example: you call this.map.mapview.animateCamera()) and that solves the problem indeed.

**Comment by gsevla** [comment]
Same problem here using it into an FC. 


Already tried using `const map =` `useRef` and `createRef`, `ref={map}` and `ref={ref => {map.current = map}`;


When I'm using an onLoad method like:

```
const onMapLoad = useCallback(() => {
    if(map.current) {console.log('a')}
    else {console.log('b')}
}, [map.current])
```

**a** is logged, but I cant execute any methods like getMapRef() or map.current.fitToCoordinates(). `map` and `map.current` are always **undefined**.

**Comment by jacquesdev** [comment]
Did anyone ever solve or resolve this issue?
