### ISSUE TITLE
No explode on tap sometimes

### ISSUE THREAD

**Issue by RWOverdijk** [novalabio/react-native-maps-super-cluster#71]
It's really difficult to reproduce I think. But, in my specific setup, on my specific device (and on other places, on other devices) I sometimes have clusters that don't explode. It just goes to the clustering zoom level, but then it doesn't actually decluster. It just centers the cluster I just tapped.

Is this behaviour something that rings any bells?

**Comment by RWOverdijk** [comment]
**Update:** on android it never explodes for me, at all. It just centers the cluster I tapped on.

**Comment by huuthinh245** [comment]
i have the same issues,  i press  on cluster it just zoom in but can't show marker. Any solution? Thank you

**Comment by RWOverdijk** [comment]
@huuthinh245 It was functional at some point after playing with the radius but I haven't been able to figure it out yet.

**Comment by 39otrebla** [comment]
@RWOverdijk could you please provide us with the code and more info about the context (number of pins, sample data, etc, etc) ?

**Comment by carloslibardo** [comment]
Same issue here, but just happen's with specific's devices, i think it's not related with the pins number inside the cluster, because i got this error with 243 pins cluster with max zoom out and a specific case that was with 2 cluster, one with 5 pins, other with 3, in the same zoom, and when i click on the cluster-3, nothing happens, in cluster-5 all works right. I think that can be something about distance between the pins inside cluster. 

I'm was using default onPress func. What u think @39otrebla ?

**Comment by RWOverdijk** [comment]
> @RWOverdijk could you please provide us with the code and more info about the context (number of pins, sample data, etc, etc) ?

@39otrebla This was in March. What do you think? haha. This is no longer a concern to me as I've implemented my own solution but I'll leave the issue open for others.

**Comment by carloslibardo** [comment]
@RWOverdijk can u share your solution here? Maybe will help other people, like me for example. =)

**Comment by RWOverdijk** [comment]
@kaduelinho I wrote my own clustering code straight from super cluster. Also keeps my data native (and the app more responsive). It's not OS I'm afraid.

**Comment by carloslibardo** [comment]
@update

I solve my problem removing edgePadding prop, i was passing a object like `{ top: 200, left: 200, bottom: 200, right: 200 }` in edgePadding config inside ClusteredMapView and this was causing impossible to render the markers inside the cluster in the view.
