### ISSUE TITLE
Edge Padding not respected on Android

### ISSUE THREAD

**Issue by benmcmaster** [novalabio/react-native-maps-super-cluster#72]
I specified `edgePadding`... It's working great on iOS, but it's not respected on Android 9.0. Is anyone else seeing this? Any workarounds?

**Comment by lpetka** [comment]
Try also setting mapPadding. Here's my config: 

- android: both mapPadding and edgePadding
- ios: mapPadding will do

**Comment by 39otrebla** [comment]
@benmcmaster I believe this is related to react-native-maps, please open the issue there.
