### ISSUE TITLE
How to get the indexes of the pins inside the cluster?

### ISSUE THREAD

**Issue by minuitagency** [novalabio/react-native-maps-super-cluster#77]
Hi, 

Thanks for the library, first one I found that works reliably,

We're working on an app that displays users on a map, we need to open the profile of the first user in the cluster when the user press on it, how would I get the index of the first user inside this cluster? 

Thanks, 

Théo

**Comment by 39otrebla** [comment]
What order are you referring to? I don't see the point. Clusters are extremely dynamic, they do depend on zoom and position on the map, so there's no real `order`. Am I missing something?
