### ISSUE TITLE
Additional data

### ISSUE THREAD

**Issue by RWOverdijk** [novalabio/react-native-maps-super-cluster#78]
Is there a way to add additional data for additional clusters that aren't part of the main data set? Using spread is too aggressive as I'm using 50k markers.

**Comment by 39otrebla** [comment]
@RWOverdijk I'm not sure I'm getting the point. For what I understood, why not just appending additional data to the data you're already passing down to the module?

**Comment by RWOverdijk** [comment]
I have no idea what this was about.
