### ISSUE TITLE
Cannot render marker if same location

### ISSUE THREAD

**Issue by tamacroft** [novalabio/react-native-maps-super-cluster#80]
Hi, i have an issue, if my location is same, it's not render marker, still in cluster number (ex : 2).
I have set key, but still not work

**Comment by nicoandriyan** [comment]
I have some issue

**Comment by Filikin** [comment]
I thought this was the way it should work.
I am thinking of examining the children in onClusterPress to see if they are if the same location and then switching to a list view if they are.
But if anyone has a better solution, I would be glad to hear it.

**Comment by Filikin** [comment]
entered up saying that if at max zoom and onClusterPress is called, then switch to list view

**Comment by nunobasto** [comment]
> entered up saying that if at max zoom and onClusterPress is called, then switch to list view

Can you tell me how you got the current zoom level?

**Comment by Filikin** [comment]
if (this.refs.clusteredMapView.getClusteringEngine().getClusterExpansionZoom(clusterId) == 20){

**Comment by 39otrebla** [comment]
@Filikin is right, this is actually how it should work. What @Filikin has already suggested seems reasonable to me. Or you can simply show a detail/preview upon [cluster press](https://github.com/novalabio/react-native-maps-super-cluster#props).

**Comment by wmonecke** [comment]
this is how I get and manage clustering by zoom level:

````
  onRegionChange = region => {
    let zoom = Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2) 

    const { clusteringEnabled } = this.state
    const maxZoomForClustering = 12

    if (zoom >= maxZoomForClustering && clusteringEnabled) {
      return this.setState({ clusteringEnabled: false })
    }

    if (zoom < maxZoomForClustering && !clusteringEnabled) {
      return this.setState({ clusteringEnabled: true })
    }
  }
````

just in case anyone need it.

````
render() {
<ClusteredMapView
          data={this.deriveArrayOfEntriesWithLocation()}
          showsCompass
          loadingEnabled
          provider={'google'}
          style={styles.flex1}
          showsTraffic={false}
          initialRegion={INIT_REGION}
          ref={ref => this.map = ref}
          renderCluster={this.renderCluster}
          onRegionChange={this.onRegionChange}
          renderMarker={this.renderClusterMarker}
          clusteringEnabled={this.state.clusteringEnabled}
          customMapStyle={GoogleMapsColorScheme[googleColorScheme]}
        >
          {!this.state.clusteringEnabled && this.renderMarker()}
        </ClusteredMapView>
}
````
