### ISSUE TITLE
Custom pointCount when cluster?

### ISSUE THREAD

**Issue by vuachom94** [novalabio/react-native-maps-super-cluster#81]
RN: 0.59

react-native-maps: jerolimov/react-native-maps#fix-rn59rc-compile-issues

I have 1 problem to solve when redner MapView i want custom number in cluster. By default it is number marker near region. Is possible to custom this number?Can you show me how thanks kiu

**Comment by 39otrebla** [comment]
We need to add a `renderCluster` prop in order to support this. We'll add this to our roadmap.

**Comment by filiptdz** [comment]
This should be already completed, I think this issue can be closed
