### ISSUE TITLE
What's the differences bewteen the initialRegion and the (MapView's) region properties ?

### ISSUE THREAD

**Issue by borgogelli** [novalabio/react-native-maps-super-cluster#86]
What's the differences bewteen the initialRegion and the (MapView's) region properties ?

**Comment by 39otrebla** [comment]
`initialRegion` is a [MapView prop](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md) as well. Please refer to the linked doc for more info and prop example usage.

**Comment by borgogelli** [comment]
Thank you
