### ISSUE TITLE
User location as initial region

### ISSUE THREAD

**Issue by AideProjet** [novalabio/react-native-maps-super-cluster#87]
Hi, 

We are trying to use the user's position as initial region, but when we pass a state to the props "initial region" the map goes to geolocation [0,0]. 

Any idea? 

Thanks, 

Théo

**Comment by DanGDroid** [comment]
Hi, @AideProjet 
try to use the map  action by its ref: `this.map.getMapRef().animateToRegion(region, duration)`
fire it up once when you receive the users position/ or when ever you want to change map location programmatically and not by map interface

ex:
```javascript
        <ClusteredMapView
            style={styles.map}
            ref={ref => { this.map = ref; }}
            ...
           />
```
```javascript
      if(this.map){
        this.map.getMapRef().animateToRegion(region, durationInMilli);
    }

```
region object:
```javascript
    {
       longitude:position.longitude,
       latitude:position.latitude,
       latitudeDelta:position.latitudeDelta || DEFAULT_LATITUDE_DELTA,
       longitudeDelta:position.longitudeDelta || DEFAULT_LONGITUDE_DELTA
   }
```

**Comment by 39otrebla** [comment]
@AideProjet `initialRegion` works as expected, I'd look into data structure/format you are passing down. Closing.
