### ISSUE TITLE
Error display map on IOS

### ISSUE THREAD

**Issue by Huy1908** [novalabio/react-native-maps-super-cluster#89]
I'm having a display problem on IOS but on android don't suffer from this problem

![a27f5b4fb5bc51e208ad](https://user-images.githubusercontent.com/41920190/61681545-07137400-ad38-11e9-95a3-f84cc278fa94.jpg)

**Comment by 39otrebla** [comment]
Could you post your code, along with more info (iOS, react-native, react-native-maps, this library versions and whether you are using MapKit or GoogleMaps )?

**Comment by 39otrebla** [comment]
Ah, I see the pic only now. I don't think this has to do with this library, [react-native-maps](https://github.com/react-native-community/react-native-maps) is the right place where to open the issue. Closing.
