### ISSUE TITLE
Custom Cluster Marker

### ISSUE THREAD

**Issue by shukerullah** [novalabio/react-native-maps-super-cluster#9]
How can I add custom image/icon with count on Cluster Marker?

**Comment by 39otrebla** [comment]
?

**Comment by brunovianarezende** [comment]
I think you should create a custom renderCluster method. Something like:

```
        <ClusteredMapView
          ...
          renderCluster={yourCustomRenderCluster}
          ...
          />
```
and then in _yourCustomRenderCluster_:

```
  yourCustomRenderCluster (cluster, onPress) {
    const { pointCount, coordinates } = cluster

    const { latitude, longitude } = coordinates

    return (
      <Marker coordinate={{ latitude, longitude }} onPress={this.onPress}>
        <TheComponentThatWillActuallyRenderTheCluster ...the properties... />
      </Marker>
    )
  }

```

**Comment by vdikun** [comment]
I second this... for me, the big difference between the different clustering options for react-native-maps is how they look... if I could control the appearance of the clusters I would not hesitate to use your library.

**Comment by 39otrebla** [comment]
This feature is under development and includes changes needed for closing #10 too. Will be released in next few days.

**Comment by 39otrebla** [comment]
#10

**Comment by 39otrebla** [comment]
Seehttps://github.com/novalabio/react-native-maps-super-cluster/commit/ee4007cc7b4d506fd40ff114bb87684b76870b2a .
