### ISSUE TITLE
Low FPS after cluster explode [ANDROID]

### ISSUE THREAD

**Issue by cernadasjuan** [novalabio/react-native-maps-super-cluster#96]
Hi!

After I perform zoom and the cluster expands, I'm getting a significant fps drop, and if I continue doing that, the fps are dropping even more. I'm using :

React native 0.59.10
React native maps 0.25
React native maps supercluster 1.6.0

In IOS, it works perfectly.

Thanks!

**Comment by carloslibardo** [comment]
Maybe having the same issue but don't know if happens the same thing into iOS: https://github.com/novalabio/react-native-maps-super-cluster/issues/97
